apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyterhub.fullname" . }}-config
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  jupyterhub_config.py: |
    {{ include "jupyterhub.config" . | nindent 4 }}

