apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  type: {{ .Values.jupyterhub.service.type }}
  ports:
    - port: {{ .Values.jupyterhub.service.port }}
      targetPort: {{ .Values.jupyterhub.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hub

